Solved cancellation signal bug
anitaa1990/Biometric-Auth-Sample pull request #9
Opened 2019-04-16 06:35 UTC by hassanmhd

Solved the cancellation signal bug by making a variable for `CancellationSignal`  for both below and above `API 23` and calling `CancellationSingnal.cancel()`  - **which requires the `minSdkVersion` to be 16**  - when the the function `onAuthenticationCancelled` is called from `MainActivity` .

Also solved the missing returns statements in `BiometricManager.authenticate()` method.

2019-04-16 07:59 UTC, mirjalal requested changes

2019-04-16 07:59 UTC, mirjalal commented on biometric-auth/build.gradle
> +        minSdkVersion 16
As fingerprint support added in Android M (API 23) and biometric API changed in API level 28, `minSdkVersion` could be changed to 23.
```suggestion
        minSdkVersion 23
```

2019-04-17 10:38 UTC, mkorat1717 commented
I have tested and its working great ! Awesome !

2019-04-29 14:44 UTC, Sammekl requested changes
Tested, works perfectly. One issue though, the minSdkVersion has been upgraded to 23 for the library, which is not necessary. In fact, it shouldn't be there. My application has minSdkVersion 21 and is in conflict with this requirement

2019-04-29 14:44 UTC, Sammekl commented on biometric-auth/build.gradle
> +        minSdkVersion 23
Why did you upgrade the minSdkVersion? This gives issues when including this library in a project which has a lower minSdkVersion.

2019-04-30 07:06 UTC, hassanmhd reviewed
Yeah you're right. I fixed it. Thank you for your feedback!

2019-04-30 07:07 UTC, hassanmhd commented
> Tested, works perfectly. One issue though, the minSdkVersion has been upgraded to 23 for the library, which is not necessary. In fact, it shouldn't be there. My application has minSdkVersion 21 and is in conflict with this requirement

Yeah you're right. I fixed it. Thank you for your feedback!

2019-04-30 07:08 UTC, hassanmhd commented on biometric-auth/build.gradle
> +        minSdkVersion 23
Fixed now. Thanks for the feedback!

2019-04-30 07:13 UTC, Sammekl commented
Great, thank you. @anitaa1990 any chance this can be merged? :)

2019-04-30 11:55 UTC, merged